// Pool of random questions for Snapcards
export const randomQuestionsPool = [
  { id: 'r1', text: "What’s your most guilty pleasure song?" },
  { id: 'r2', text: "Describe the funniest thing you’ve ever done on a dare." },
  { id: 'r3', text: "If you could time-travel, what one moment in crypto history would you visit?" },
  { id: 'r4', text: "What’s the weirdest food you’ve ever tried—and did you actually like it?" },
  { id: 'r5', text: "Which childhood cartoon character would make the worst DAO member?" },
  { id: 'r6', text: "What’s a habit you wish you could break (but secretly enjoy)?" },
  { id: 'r7', text: "If you could have dinner with any three people—dead or alive—who’d you pick?" },
  { id: 'r8', text: "What’s the craziest item on your personal bucket list?" },
  { id: 'r9', text: "Which movie can you quote start to finish without missing a line?" },
  { id: 'r10', text: "What’s the boldest compliment you’ve ever received?" },
  { id: 'r11', text: "If you could instantly master any skill—crypto or IRL—which one?" },
  { id: 'r12', text: "What’s your go-to comfort food after a long day?" },
  { id: 'r13', text: "What’s the most adventurous thing you’ve ever done (Web3 or otherwise)?" },
  { id: 'r14', text: "Tell us about a lie you once told your parents (we won’t tell!)." },
  { id: 'r15', text: "If you could live anywhere in the world, crypto-friendly or not, where?" },
  { id: 'r16', text: "How do you unwind—Netflix binge, paper trading, or something crazier?" },
  { id: 'r17', text: "Which trending meme token do you low-key believe in?" },
  { id: 'r18', text: "What’s the single most valuable life lesson you’ve learned so far?" },
  { id: 'r19', text: "Favorite childhood memory that still makes you smile?" },
  { id: 'r20', text: "If you could be famous for one outrageous thing, what would it be?" },
  { id: 'r21', text: "What’s the dumbest gas fee you’ve ever paid, and why was it worth it?" },
  { id: 'r22', text: "Which NFT in your wallet embarrasses you the most?" },
  { id: 'r23', text: "What’s your worst DeFi rug-pull story?" },
  { id: 'r24', text: "Name a protocol you secretly think is totally overrated." },
  { id: 'r25', text: "What’s the best piece of crypto advice you’ve ever ignored?" },
  { id: 'r26', text: "What's the worst hackathon bug you’ve ever chased down at 3 AM?" },
  { id: 'r27', text: "Which hackathon pitch made you think, 'Should I have just ordered pizza instead?' " },
  { id: 'r28', text: "Which keynote speaker at a Web3 event gave you the biggest cringe moment?" },
  { id: 'r29', text: "What's the most ridiculous swag you've ever hauled home from a crypto conference?" },
  { id: 'r30', text: "If your wallet could talk, what embarrassing secret would it spill?" },
  { id: 'r31', text: "What’s the wildest after-party you crashed post-DAO summit?" },
  { id: 'r32', text: "Describe a gas-fee fail that cost you more than your lunch." },
  { id: 'r33', text: "What’s the most eyebrow-raising NFT you saw minted live on stage?" },
  { id: 'r34', text: "If you could rename Ethereum to something hilarious, what would it be?" },
  { id: 'r35', text: "Which hackathon challenge made you bail because it felt impossible?" },
  { id: 'r36', text: "What’s the funniest team name you’ve seen at a Web3 hackathon?" },
  { id: 'r37', text: "Share your worst 'sold too early' token story." },
  { id: 'r38', text: "Which icebreaker question at a meetup made you want to run?" },
  { id: 'r39', text: "Best—and worst—drink you had at a project launch after-party?" },
  { id: 'r40', text: "What’s the weirdest on-chain data you’ve ever explored on Etherscan?" },
  { id: 'r41', text: "What’s your go‑to excuse for ghosting a Web3 meetup?" },
  { id: 'r42', text: "If you could stake any fictional character, who’d you pick and why?" },
  { id: 'r43', text: "Which crypto meme never fails to make you laugh?" },
  { id: 'r44', text: "Which hackathon project do you secretly dream of building?" },
  { id: 'r45', text: "If you could time‑travel to any ICO, which one and why?" }
];
